[package]
name = "vimhack"
version = "0.1.0"
authors = ["Rich Churcher <rich.churcher@gmail.com>"]
edition = "2018"

[dependencies]
rltk = { version = "0.7.0" }
specs = "0.16.1"
specs-derive = "0.4.1"
